workspace:
  base: /test
  path: src/github.com/CJTSAJ/drone
pipeline:
  build:
    image: node:latest
    commands:
      - npm install
      - npm run dist
  publish:
    image: plugin/docker
    repo: CJTSAJ/drone
    tags: ["latest", "v2"]
    dockerfile: Dockerfile